import { Model } from 'mongoose';
import * as bcrypt from 'bcrypt';
import { UserDocument } from '../../models/user.schema';
import { PrivilegesDocument } from '../../models/privilege.schema';
import { Role } from '../../utils/role.enum';

export async function seedSuperAdminUser(
  userModel: Model<UserDocument>,
  privilegeModel: Model<PrivilegesDocument>,
): Promise<void> {
  try {
    const username = 'anees';
    const email = 'aneespengad4447@gmail.com';
    const rawPassword = '000000';

    const superAdminPrivilege = await privilegeModel.findOne({
      $or: [{ name: Role.superadmin }, { roles: Role.superadmin }],
      isDeleted: false,
    });

    if (!superAdminPrivilege) {
      console.warn(
        '[SEED] System superadmin privilege not yet generated by PrivilegeService. Will retry on next boot.',
      );
      return;
    }

    const existingSuperAdmin = await userModel.findOne({
      $or: [{ username }, { email }],
      isDeleted: false,
    });

    if (!existingSuperAdmin) {
      const hashedPassword = await bcrypt.hash(rawPassword, 10);
      await userModel.create({
        username,
        name: 'Anees (Super Admin)',
        email,
        password: hashedPassword,
        privilegeId: superAdminPrivilege._id,
        companyId: null,
        isActive: true,
      });
      console.log(
        `[SEED] Super Admin user '${username}' (${email}) seeded successfully using system privilege '${superAdminPrivilege.name}'`,
      );
    } else if (!existingSuperAdmin.privilegeId) {
      await userModel.updateOne(
        { _id: existingSuperAdmin._id },
        { $set: { privilegeId: superAdminPrivilege._id } },
      );
    }
  } catch (error: unknown) {
    console.warn('[SEED] Error seeding Super Admin user:', error);
  }
}
