export const SUB_MODULES = {
  COMPANY: 'company',
  USER: 'user',
  PRIVILEGE: 'privilege',
  SUBSCRIPTION: 'subscription',
  CATEGORY: 'category',
  BRAND: 'brand',
  PRODUCT: 'product',
  SUPPLIER: 'supplier',
  PURCHASE: 'purchase',
  CUSTOMER: 'customer',
  REGISTER: 'register',
  SALE: 'sale',
  EXPENSE: 'expense',
} as const;
