export enum LogStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
}

export enum LogActions {
  // Company
  CREATE_COMPANY = 'CREATE_COMPANY',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  DELETE_COMPANY = 'DELETE_COMPANY',

  // User
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Privilege
  CREATE_PRIVILEGE = 'CREATE_PRIVILEGE',
  UPDATE_PRIVILEGE = 'UPDATE_PRIVILEGE',
  DELETE_PRIVILEGE = 'DELETE_PRIVILEGE',

  // Subscription
  CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION',
  UPDATE_SUBSCRIPTION = 'UPDATE_SUBSCRIPTION',
  DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION',

  // Unit
  CREATE_UNIT = 'CREATE_UNIT',
  UPDATE_UNIT = 'UPDATE_UNIT',
  DELETE_UNIT = 'DELETE_UNIT',

  // Subscription Plan
  CREATE_SUBSCRIPTION_PLAN = 'CREATE_SUBSCRIPTION_PLAN',
  UPDATE_SUBSCRIPTION_PLAN = 'UPDATE_SUBSCRIPTION_PLAN',
  DELETE_SUBSCRIPTION_PLAN = 'DELETE_SUBSCRIPTION_PLAN',
}

export enum LogEntityType {
  COMPANY = 'Company',
  USER = 'User',
  PRIVILEGE = 'Privilege',
  SUBSCRIPTION = 'Subscription',
  UNIT = 'Unit',
  SUBSCRIPTION_PLAN = 'SubscriptionPlan',
}
