export enum LogStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
}

export enum PaperWidth {
  MM_58 = '58mm',
  MM_80 = '80mm',
}

export enum numberSettingsDocumentType {
  INVOICE = 'INVOICE',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  BILL = 'BILL',
}

export enum RefundMethod {
  CASH = 'CASH',
  CARD = 'CARD',
  UPI = 'UPI',
  STORE_CREDIT = 'STORE_CREDIT',
}

export enum LogActions {
  // Company
  CREATE_COMPANY = 'CREATE_COMPANY',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  DELETE_COMPANY = 'DELETE_COMPANY',

  // User
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Privilege
  CREATE_PRIVILEGE = 'CREATE_PRIVILEGE',
  UPDATE_PRIVILEGE = 'UPDATE_PRIVILEGE',
  DELETE_PRIVILEGE = 'DELETE_PRIVILEGE',

  // Subscription
  CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION',
  UPDATE_SUBSCRIPTION = 'UPDATE_SUBSCRIPTION',
  DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION',

  // Unit
  CREATE_UNIT = 'CREATE_UNIT',
  UPDATE_UNIT = 'UPDATE_UNIT',
  DELETE_UNIT = 'DELETE_UNIT',

  // Subscription Plan
  CREATE_SUBSCRIPTION_PLAN = 'CREATE_SUBSCRIPTION_PLAN',
  UPDATE_SUBSCRIPTION_PLAN = 'UPDATE_SUBSCRIPTION_PLAN',
  DELETE_SUBSCRIPTION_PLAN = 'DELETE_SUBSCRIPTION_PLAN',

  // Category
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',

  // Brand
  CREATE_BRAND = 'CREATE_BRAND',
  UPDATE_BRAND = 'UPDATE_BRAND',
  DELETE_BRAND = 'DELETE_BRAND',

  // Product
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  // Supplier
  CREATE_SUPPLIER = 'CREATE_SUPPLIER',
  UPDATE_SUPPLIER = 'UPDATE_SUPPLIER',
  DELETE_SUPPLIER = 'DELETE_SUPPLIER',

  // Purchase
  CREATE_PURCHASE = 'CREATE_PURCHASE',
  UPDATE_PURCHASE = 'UPDATE_PURCHASE',
  DELETE_PURCHASE = 'DELETE_PURCHASE',

  // Customer
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  UPDATE_CUSTOMER = 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER = 'DELETE_CUSTOMER',

  // Register Session / Shift
  OPEN_REGISTER = 'OPEN_REGISTER',
  CLOSE_REGISTER = 'CLOSE_REGISTER',

  // Sale
  CREATE_SALE = 'CREATE_SALE',
  HOLD_SALE = 'HOLD_SALE',
  CANCEL_SALE = 'CANCEL_SALE',
  PRINT_SALE = 'PRINT_SALE',

  // Sale Return & Refund
  CREATE_SALE_RETURN = 'CREATE_SALE_RETURN',
  DELETE_SALE_RETURN = 'DELETE_SALE_RETURN',

  // Expense
  CREATE_EXPENSE = 'CREATE_EXPENSE',
  DELETE_EXPENSE = 'DELETE_EXPENSE',

  // Number Settings
  UPDATE_NUMBER_SETTING = 'UPDATE_NUMBER_SETTING',

  // Printer
  CREATE_PRINTER = 'CREATE_PRINTER',
  UPDATE_PRINTER = 'UPDATE_PRINTER',
  DELETE_PRINTER = 'DELETE_PRINTER',

  // Counter
  CREATE_COUNTER = 'CREATE_COUNTER',
  UPDATE_COUNTER = 'UPDATE_COUNTER',
  DELETE_COUNTER = 'DELETE_COUNTER',

  // Label Designer
  GENERATE_LABEL = 'GENERATE_LABEL',

  // Staff
  CREATE_STAFF = 'CREATE_STAFF',
  UPDATE_STAFF = 'UPDATE_STAFF',
  DELETE_STAFF = 'DELETE_STAFF',
}

export enum LogEntityType {
  COMPANY = 'Company',
  USER = 'User',
  PRIVILEGE = 'Privilege',
  SUBSCRIPTION = 'Subscription',
  UNIT = 'Unit',
  SUBSCRIPTION_PLAN = 'SubscriptionPlan',
  CATEGORY = 'Category',
  BRAND = 'Brand',
  PRODUCT = 'Product',
  SUPPLIER = 'Supplier',
  PURCHASE = 'Purchase',
  CUSTOMER = 'Customer',
  REGISTER_SESSION = 'RegisterSession',
  SALE = 'Sale',
  SALE_RETURN = 'SaleReturn',
  EXPENSE = 'Expense',
  NUMBER_SETTING = 'NumberSetting',
  PRINTER = 'Printer',
  COUNTER = 'Counter',
  LABEL_DESIGNER = 'LabelDesigner',
  STAFF = 'Staff',
}
